services:
  postgres:
    image: postgres:13

    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-db-volume/data:/var/lib/postgresql/data
      - ./postgres-db-volume/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
    networks:
      - my_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
  
  af:
    container_name: airflow-webserver
    build:
      context: ./custom_images/airflow_dbt
      dockerfile: Dockerfile

    ports:
      - "8000:8080"
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_meta:airflow_pass@postgres:5432/airflow_db 
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt_app:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my_network
    command: >
      bash -c "dbt init weather_etl --profile weather_etl && airflow db migrate && airflow standalone "
      bash -c "airflow db migrate && airflow standalone "

networks:
  my_network:
    driver: bridge

        
